version: 2.1

orbs:
  node: circleci/node@1.0.1
  gcp-gke: circleci/gcp-gke@0.1.0
  gcr: circleci/gcp-gcr@0.0.2

jobs:
  build:
    docker:
      - image: google/cloud-sdk
# this google image will already have gcloud and kubectl and docker in docker
#        otherwise need to create custom image with all apps and capability like kubectl and

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Login to Docker
          command: echo $D_PASS | docker login -u $D_USER --password-stdin

#i#`get the commit hash and use it as a tag.
#git log --format="%H"  > TAG
#circleci will already have in env GIT_SHA1
#echo 'export GIT_SHA1='$CIRCLE_SHA1'' >> $BASH_ENV

      - run:
          name: Build the mysql image
          command: docker build -t davesav/mysql:${CIRCLE_SHA1} my-mysql

      - run:
          name: Push mysql to dockerhub
          command: docker push davesav/mysql:${CIRCLE_SHA1}

      - run:
          name: Build the wp image
          command: docker build -t davesav/wp:${CIRCLE_SHA1} my-wp

      - run:
          name: Push wp to dockerhub
          command: docker push davesav/wp:${CIRCLE_SHA1}

#
# Get creds for cluster and push new images

      - run:
          name: Grant k8s permissions into cluster
          command: |
            cd $HOME

            echo "Project: ${GKE_PROJECT_ID}"
            gcloud config set project ${GKE_PROJECT_ID}
            echo "Compute Zone: ${GKE_COMPUTE_ZONE}"
            gcloud config set compute/zone ${GKE_COMPUTE_ZONE}

            echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
            echo "${GKE_SERVICE_ACCOUNT}" | base64 --decode --ignore
            echo "${GKE_SERVICE_ACCOUNT}" | base64 --decode --ignore > /tmp/gke_key.json
            echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
            gcloud auth activate-service-account --key-file /tmp/gke_key.json

            gcloud container clusters get-credentials ${GKE_CLUSTER_NAME}


# Push the new images to cluster

      - run:
          name: Notify k8s to use the new wp and mysql images 
          command: |
            echo "Hash / image tag: ${CIRCLE_SHA1}"
            kubectl get deploy
            kubectl set image deployment/wp wp=davesav/wp:${CIRCLE_SHA1}
            kubectl annotate deployment.v1.apps/wp kubernetes.io/change-cause=${CIRCLE_SHA1}
            kubectl set image deployment/mysql mysql=davesav/mysql:${CIRCLE_SHA1}
            kubectl annotate deployment.v1.apps/mysql kubernetes.io/change-cause=${CIRCLE_SHA1}
            kubectl get deploy
